window.DEMO_SUMMARY = {
  total_polizas: 7261,
  activas: 1200,
  base_churn_temprano: 0.255,
  alto: 55,
  medio: 1118,
  bajo: 27,
  precision_top20_entregable_3: 0.491,
  roc_auc_entregable_3: 0.731,
  modelo_entregable_3: "XGBoost",
  prototipo: "Demo web estatica + API local opcional"
};

window.DEMO_POLICIES = [
  {
    id_poliza: "DEMO-001",
    numero_poliza: "96316987",
    patente: "LST097",
    cliente: "Cliente demo 01",
    email: "cl***@demo.com",
    telefono: "***9290",
    estado: "activated",
    aseguradora: "zurich",
    cobertura: "Terceros completo",
    metodo_pago: "bankAccount",
    region: "GBA",
    provincia: "Buenos Aires",
    marca: "CITROEN",
    modelo: "C 3 PICASSO 1.6I SX",
    fecha_inicio: "2025-09-08",
    cuota: "172.741",
    comision: "26.670",
    score_churn: 0.455,
    nivel_riesgo: "Alto",
    accion_recomendada: "Contactar en la primera semana y revisar dolor de precio/cobertura.",
    razones: [
      { label: "cuota", text: "Cuota mensual alta", impact: 0.11 },
      { label: "aseguradora", text: "Aseguradora con mayor churn historico", impact: 0.10 },
      { label: "renovacion", text: "Poliza nueva, no renovacion", impact: 0.06 }
    ]
  },
  {
    id_poliza: "DEMO-002",
    numero_poliza: "90006347993",
    patente: "OZR997",
    cliente: "Cliente demo 02",
    email: "cl***@demo.com",
    telefono: "***5358",
    estado: "activated",
    aseguradora: "zurich",
    cobertura: "Terceros completo con granizo",
    metodo_pago: "bankAccount",
    region: "GBA",
    provincia: "Buenos Aires",
    marca: "TOYOTA",
    modelo: "COROLLA 1.8 XEI",
    fecha_inicio: "2025-10-15",
    cuota: "211.274",
    comision: "33.253",
    score_churn: 0.455,
    nivel_riesgo: "Alto",
    accion_recomendada: "Contactar en la primera semana y revisar dolor de precio/cobertura.",
    razones: [
      { label: "cuota", text: "Cuota mensual alta", impact: 0.11 },
      { label: "aseguradora", text: "Aseguradora con mayor churn historico", impact: 0.10 },
      { label: "pago", text: "Metodo de pago CBU", impact: 0.06 }
    ]
  },
  {
    id_poliza: "DEMO-003",
    numero_poliza: "516526560",
    patente: "AF977MQ",
    cliente: "Cliente demo 03",
    email: "cl***@demo.com",
    telefono: "***4043",
    estado: "activated",
    aseguradora: "mercantilAndina",
    cobertura: "Todo riesgo franquicia alta",
    metodo_pago: "creditCard",
    region: "Interior",
    provincia: "Entre Rios",
    marca: "CHEVROLET",
    modelo: "CRUZE 1.4 PREMIER AT",
    fecha_inicio: "2025-12-19",
    cuota: "85.072",
    comision: "10.044",
    score_churn: 0.342,
    nivel_riesgo: "Medio",
    accion_recomendada: "Seguimiento preventivo durante onboarding.",
    razones: [
      { label: "aseguradora", text: "Aseguradora con riesgo medio-alto", impact: 0.05 },
      { label: "renovacion", text: "Poliza nueva, no renovacion", impact: 0.06 }
    ]
  },
  {
    id_poliza: "DEMO-004",
    numero_poliza: "594919924",
    patente: "AG701WM",
    cliente: "Cliente demo 04",
    email: "cl***@demo.com",
    telefono: "***5447",
    estado: "activated",
    aseguradora: "sura",
    cobertura: "Terceros completo premium",
    metodo_pago: "creditCard",
    region: "CABA",
    provincia: "Capital Federal",
    marca: "FORD",
    modelo: "TERRITORY TITANIUM",
    fecha_inicio: "2026-01-24",
    cuota: "230.364",
    comision: "27.055",
    score_churn: 0.443,
    nivel_riesgo: "Alto",
    accion_recomendada: "Contactar en la primera semana y revisar dolor de precio/cobertura.",
    razones: [
      { label: "cuota", text: "Cuota mensual alta", impact: 0.11 },
      { label: "aseguradora", text: "Aseguradora con churn sobre promedio", impact: 0.08 },
      { label: "cobertura", text: "Cobertura de terceros", impact: 0.04 }
    ]
  },
  {
    id_poliza: "DEMO-005",
    numero_poliza: "2324485910",
    patente: "AE064VW",
    cliente: "Cliente demo 05",
    email: "cl***@demo.com",
    telefono: "***7718",
    estado: "activated",
    aseguradora: "allianz",
    cobertura: "Terceros completo",
    metodo_pago: "creditCard",
    region: "GBA",
    provincia: "Buenos Aires",
    marca: "FIAT",
    modelo: "ARGO 1.8 PRECISION",
    fecha_inicio: "2025-08-20",
    cuota: "84.691",
    comision: "12.161",
    score_churn: 0.244,
    nivel_riesgo: "Medio",
    accion_recomendada: "Seguimiento preventivo durante onboarding.",
    razones: [
      { label: "renovacion", text: "Poliza nueva, no renovacion", impact: 0.06 },
      { label: "cobertura", text: "Cobertura de terceros", impact: 0.04 }
    ]
  },
  {
    id_poliza: "DEMO-006",
    numero_poliza: "90289716",
    patente: "AD986CJ",
    cliente: "Cliente demo 06",
    email: "cl***@demo.com",
    telefono: "***1867",
    estado: "activated",
    aseguradora: "experta",
    cobertura: "Todo riesgo franquicia baja",
    metodo_pago: "creditCard",
    region: "CABA",
    provincia: "Capital Federal",
    marca: "CHRYSLER",
    modelo: "JEEP RENEGADE SPORT",
    fecha_inicio: "2025-10-30",
    cuota: "122.840",
    comision: "19.224",
    score_churn: 0.196,
    nivel_riesgo: "Bajo",
    accion_recomendada: "Flujo normal de onboarding.",
    razones: [
      { label: "cuota", text: "Cuota mensual media-alta", impact: 0.06 }
    ]
  }
];
